{
 "title": "Flask Backend Monitoring Dashboard",
 "tags": [
  "flask",
  "prometheus",
  "grafana",
  "devops"
 ],
 "time": { "from": "now-15m", "to": "now" },
 "refresh": "10s",
 "panels": [
  {
   "title": "Flask Backend Status",
   "type": "stat",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "up{job=\"flask-backend\"}"
    }
   ]
  },
  {
   "title": "Prometheus Status",
   "type": "stat",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "up{job=\"prometheus\"}"
    }
   ]
  },
  {
   "title": "Request Rate",
   "type": "stat",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(rate(flask_http_request_total[1m]))"
    }
   ]
  },
  {
   "title": "HTTP Request Rate",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "rate(flask_http_request_total[1m])",
     "legendFormat": "{{method}} {{status}}"
    }
   ]
  },
  {
   "title": "HTTP Request Count",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 7 },
   "targets": [
    {
     "expr": "flask_http_request_duration_seconds_count",
     "legendFormat": "{{method}} {{path}} {{status}}"
    }
   ]
  }
 ]
}