apiVersion: apps/v1
kind: Deployment
metadata:
  name: flask-backend
spec:
  replicas: 2
  selector:
    matchLabels:
      app: flask-backend
  template:
    metadata:
      labels:
        app: flask-backend
    spec:
      containers:
        - name: flask-backend
          image: devops-production-platform-backend:latest
          ports:
            - containerPort: 5000
          env:
            - name: DATABASE_URL
              value: "https://devops-production-platform.onrender.com/"
