apiVersion: apps/v1
kind: Deployment
metadata:
  name: flask-backend
  namespace: devops-platform
  labels:
    app: flask-backend

spec:
  replicas: 2

  selector:
    matchLabels:
      app: flask-backend

  template:
    metadata:
      labels:
        app: flask-backend

    spec:
      containers:
        - name: flask-backend
          image: YOUR_DOCKERHUB_USERNAME/flask-backend:latest
          imagePullPolicy: Always

          ports:
            - containerPort: 5000

          env:
            - name: DATABASE_URL
              valueFrom:
                secretKeyRef:
                  name: flask-secrets
                  key: DATABASE_URL

          resources:
            requests:
              memory: "128Mi"
              cpu: "100m"
            limits:
              memory: "512Mi"
              cpu: "500m"

          livenessProbe:
            httpGet:
              path: /health
              port: 5000
            initialDelaySeconds: 10
            periodSeconds: 10

          readinessProbe:
            httpGet:
              path: /health
              port: 5000
            initialDelaySeconds: 5
            periodSeconds: 5