apiVersion: apps/v1
kind: Deployment

metadata:
  name: flask-backend
  namespace: devops-platform
  labels:
    app: flask-backend
    component: backend

spec:
  replicas: 2

  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 1
      maxSurge: 1

  selector:
    matchLabels:
      app: flask-backend

  template:
    metadata:
      labels:
        app: flask-backend
        component: backend

    spec:
      containers:
        - name: flask-backend

          image: devops-production-platform-backend:latest
          imagePullPolicy: IfNotPresent

          ports:
            - name: http
              containerPort: 5000

          env:
            - name: DATABASE_URL
              valueFrom:
                secretKeyRef:
                  name: flask-secret
                  key: DATABASE_URL

            - name: FLASK_ENV
              valueFrom:
                configMapKeyRef:
                  name: flask-config
                  key: FLASK_ENV

            - name: APP_NAME
              valueFrom:
                configMapKeyRef:
                  name: flask-config
                  key: APP_NAME

          resources:
            requests:
              cpu: "250m"
              memory: "256Mi"

            limits:
              cpu: "500m"
              memory: "512Mi"

          readinessProbe:
            httpGet:
              path: /health
              port: 5000
            initialDelaySeconds: 10
            periodSeconds: 5
            timeoutSeconds: 3
            failureThreshold: 3

          livenessProbe:
            httpGet:
              path: /health
              port: 5000
            initialDelaySeconds: 20
            periodSeconds: 10
            timeoutSeconds: 5
            failureThreshold: 3