apiVersion: v1
kind: ConfigMap
metadata:
  name: flask-config
  namespace: devops-platform
<<<<<<< HEAD

data:
  FLASK_ENV: "production"
  APP_NAME: "devops-production-platform"
  APP_PORT: "5000"
=======
  labels:
    app: flask-backend
data:
  FLASK_ENV: "production"
>>>>>>> 99f4b14 (Improve DevOps project structure and configs)
